### ISSUE TITLE
[Question] Does redistimeseries-go offer string data insertion.

### ISSUE THREAD

**Issue by iAmSKU** [RedisTimeSeries/redistimeseries-go#143]
Hello,

I have a question on the string data ingestion to redis-timeseries.

When I insert numeric data to redis-timeseries:
```
127.0.0.1:6379> TS.ADD tag1 1626434637914 26
(integer) 1626434637914
```

Data was successfully inserted, but when I try to add string data, I get the following error:

```
127.0.0.1:6379> TS.ADD tag2 1626434637915 "my-data"
(error) ERR TSDB: invalid value
```

Also when I look to the library side, there is no possibility to add string data:
storedTimeStamp, err := redisTS.AddAutoTsWithOptions("record", (float64)(dataPayload.RecordId), options)
	
As per my understand, it seems redistimeseries does not support string data insertion.  After some research label is a way but that usecase is mainly for grouping the data. 

Is my understanding correct or there is any other way to insert string data?

**Comment by LiorKogan** [comment]
That is correct. You cannot insert strings, only floating-point values.
