### ISSUE TITLE
Request for MultiGetWithOptions

### ISSUE THREAD

**Issue by stevesim101** [RedisTimeSeries/redistimeseries-go#64]
Please add the ability to run a TS.MGET with options (i.e., optional args) to this package.  We need to run TS.MGET with the arg WITHLABELS.

Example:
TS.MGET WITHLABELS filter type=foo id=1

**Comment by filipecosta90** [comment]
hi there @stevesim101 we will gladly do so :) Thank you for the feedback :+1:

**Comment by filipecosta90** [comment]
hi there @stevesim101 #67 has been merged and you should be able to try it with the current master :) 
We should release shortly a new version.

**Comment by stevesim101** [comment]
Thank you @filipecosta90 for the quick turnaround!

**Comment by stevesim101** [comment]
@filipecosta90 - Yes, please create a new release.  The current 1.2.1 release is missing this and other commits from May 8 and May 11.  We use vendoring in our go projects for external packages.  So running `go mod vendor` only pulls from your latest release.

**Comment by filipecosta90** [comment]
> @filipecosta90 - Yes, please create a new release. The current 1.2.1 release is missing this and other commits from May 8 and May 11. We use vendoring in our go projects for external packages. So running `go mod vendor` only pulls from your latest release.

hi there @stevesim101 , we've just released [1.3.0](https://github.com/RedisTimeSeries/redistimeseries-go/releases/tag/v1.3.0) with the requested feature included :)
