### ISSUE TITLE
Support for TS.MREVRANGE

### ISSUE THREAD

**Issue by filipecosta90** [RedisTimeSeries/redistimeseries-go#65]
Further reference: https://oss.redislabs.com/redistimeseries/commands/#tsmrangetsmrevrange

**Comment by stevesim101** [comment]
Hi @filipecosta90.  Thank you for submitting this issue.  We didn't realize TS.MREVRANGE missing from the package.  We just discovered a need for this in our own project.  Is there any chance this would be ready by the end of the week?  It will be a tremendous benefit!

**Comment by filipecosta90** [comment]
hi there @stevesim101 the following PR should solve it https://github.com/RedisTimeSeries/redistimeseries-go/pull/70
As soon as we review it and iterate over it, I'll update back :)
