### ISSUE TITLE
Support for TS.REVRANGE

### ISSUE THREAD

**Issue by filipecosta90** [RedisTimeSeries/redistimeseries-go#66]
Further reference: https://oss.redislabs.com/redistimeseries/commands/#tsrangetsrevrange

**Comment by stevesim101** [comment]
Hi @filipecosta90. Thank you for submitting this issue. We didn't realize TS.REVRANGE missing from the package. We just discovered a need for this in our own project. Is there any chance this would be ready by the end of the week? It will be a tremendous benefit!

**Comment by filipecosta90** [comment]
Hi there @stevesim101, I believe that implementing it should be really straightforward.  I'll keep this issue updated :)

**Comment by stevesim101** [comment]
Thank you very much!

**Comment by filipecosta90** [comment]
hi there @stevesim101 the following PR should solve it https://github.com/RedisTimeSeries/redistimeseries-go/pull/70
As soon as we review it and iterate over it, I'll update back :)

**Comment by stevesim101** [comment]
@filipecosta90 - Do you have an ETA as to when the new release will be created?  Thanks!

**Comment by filipecosta90** [comment]
> @filipecosta90 - Do you have an ETA as to when the new release will be created? Thanks!

hi there @stevesim101 , right now. We've just release [v1.4.0](https://github.com/RedisTimeSeries/redistimeseries-go/releases/tag/v1.4.0). 
Thank you for briging this up and please share feedback on whether it solved the problem/how easy it was/etc... :)

**Comment by stevesim101** [comment]
@filipecosta90 - The latest release of this package is terrific!  We were able to easily integrate the new timeseries functions into our project.  The performance of the timeseries client is fantastic!!  Thanks again for your help pushing these issues to completion in a timely manner.
